---
name: callee
run-name: Callee [${{ inputs.job_id && inputs.job_id || '' }}]

on:
    workflow_dispatch:
        inputs:
            job_id:
                description: "the job ID"
                required: true
                type: string

            source_run_id:
                description: "the run ID that triggered this workflow"
                required: false
                type: string

    workflow_call:
        inputs:
            job_id:
                description: "the job ID"
                required: true
                type: string

            source_run_id:
                description: "the run ID that triggered this workflow"
                required: false
                type: string


concurrency:
    group: "${{ github.workflow }}"
    cancel-in-progress: false

jobs:
    find-and-update-comment:
        runs-on: ubuntu-latest
        steps:
            -   run: echo ohai

            -   name: Checkout repository
                uses: actions/checkout@v4

            -   run: |
                    cat >> "${GITHUB_STEP_SUMMARY}" <<- '__summary'

                    ## inputs

                    ```json
                    ${{ toJSON(inputs) }}
                    ```

                    my real run id: ${{ github.run_id }}
                    __summary

            -   uses: namespacelabs/breakpoint-action@v0
                # if: always()
                with:
                    authorized-users: blalor
