---
name: callee
run-name: Callee [${{ inputs.job_id && inputs.job_id || '' }}]

on:
    workflow_dispatch:
        inputs:
            job_id:
                description: "the job ID"
                required: true
                type: string

            source_run_id:
                description: "the run ID that triggered this workflow"
                required: false
                type: string

    workflow_call:
        inputs:
            job_id:
                description: "the job ID"
                required: true
                type: string

            source_run_id:
                description: "the run ID that triggered this workflow"
                required: false
                type: string


concurrency:
    group: "${{ github.workflow }}"
    cancel-in-progress: false

jobs:
    find-and-update-comment:
        permissions:
            contents: read
            actions: read # allow reading the run info

        runs-on: ubuntu-latest

        steps:
            -   run: echo ${{ github.workflow }}

            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: dump contexts
                shell: bash
                run: |-
                    set -e

                    cat <<-'__ctx' >| context-github.json
                    {
                        "github": ${{ toJSON(github) }},
                        "inputs": ${{ toJSON(inputs) }},
                        "env": ${{ toJSON(env) }}
                    }
                    __ctx

            -   name: get run info
                shell: bash
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}

            -   name: upload artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: contexts-${{ github.job }}
                    path: context-*.json
