---
name: callee
run-name: Comment on PR [${{ inputs.job_id && inputs.job_id || '' }}]

on:
    workflow_call:
        inputs:
            job_id:
                description: "the job ID"
                required: true
                type: string

            source_run_id:
                description: "the run ID that triggered this workflow"
                required: false
                type: number


concurrency:
    group: "${{ github.workflow }}"
    cancel-in-progress: false

jobs:
    find-and-update-comment:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   run: |
                    cat >> "${GITHUB_STEP_SUMMARY}" <<- '__summary'

                    ## inputs

                    ```json
                    ${{ toJSON(inputs) }}
                    ```
