---
name: caller
run-name: invoke callee [${{ inputs.job_id && inputs.job_id || '' }}]

on:
    workflow_dispatch:
        inputs:
            job_id:
                description: "the job ID"
                required: true
                type: string

jobs:
    dummy:
        runs-on: ubuntu-latest
        steps:
            -   run: echo ${{ github.workflow }}

            -   name: dump contexts
                shell: bash
                run: |-
                    set -e

                    cat <<-'__ctx' >| context-github.json
                    {
                        "github": ${{ toJSON(github) }},
                        "inputs": ${{ toJSON(inputs) }},
                        "env": ${{ toJSON(env) }}
                    }
                    __ctx

            -   name: upload artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: contexts-${{ github.job }}
                    path: context-*.json

    # comment-on-pr:
    #     runs-on: ubuntu-latest

    #     permissions:
    #         contents: read
    #         actions: write # allow dispatching the other workflow

    #     steps:
    #         -   name: dispatch
    #             shell: bash
    #             env:
    #                 GH_TOKEN: ${{ github.token }}
    #             run: |
    #                 gh workflow run \
    #                     callee.yaml \
    #                     --repo ${{ github.repository }} \
    #                     --ref ${{ github.ref_name }} \
    #                     --raw-field job_id=${{ inputs.job_id }} \
    #                     --raw-field source_run_id=${{ github.run_id }}

    call-callee:
        uses: blalor/actions-test-reusable/.github/workflows/callee.yaml@main
