---
name: caller
run-name: invoke callee [${{ inputs.job_id && inputs.job_id || '' }}]

on:
    workflow_dispatch:
        inputs:
            job_id:
                description: "the job ID"
                required: true
                type: string

jobs:
    dummy:
        runs-on: ubuntu-latest
        steps:
            -   run: echo ${{ github.workflow }}

            -   name: dump contexts
                shell: bash
                run: |-
                    set -e

                    cat <<-'__ctx' >| context-github.json
                    {
                        "github": ${{ toJSON(github) }},
                        "inputs": ${{ toJSON(inputs) }},
                        "env": ${{ toJSON(env) }},
                    }
                    __ctx

            -   name: upload artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: contexts-${{ github.job }}
                    path: context-*.json

    comment-on-pr:
        name: call callee
        uses: ./.github/workflows/callee.yaml
        with:
            job_id: ${{ inputs.job_id }}
            source_run_id: ${{ github.run_id }}
            trigger_ts: ${{ github.event.repository.pushed_at }}
