---
name: do the thing

on:
    push:
        branches:
            - main

    pull_request:


jobs:
    "j-o-b":
        name: job
        runs-on: ubuntu-latest

        steps:
            -   name: dump github context
                shell: bash
                run: |-
                    set -e

                    cat <<-'__ctx' >| context-github.json
                    ${{ toJSON(github) }}
                    __ctx

            -   name: dump inputs context
                shell: bash
                run: |-
                    set -e

                    cat <<-'__ctx' >| context-inputs.json
                    ${{ toJSON(inputs) }}
                    __ctx

            -   name: dump env context
                shell: bash
                run: |-
                    set -e

                    cat <<-'__ctx' >| context-env.json
                    ${{ toJSON(env) }}
                    __ctx

            -   name: upload artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: contexts
                    path: context-*.json
