---
name: do the thing
run-name: "thinging on ${{ github.event_name }}, #${{ github.event.run_number }}"

on:
    push:
        branches:
            - main

    pull_request:


env:
    COMMIT_HASH: "${{ github.event.pull_request.head.sha || github.sha }}"
    BRANCH: "${{ github.head_ref || github.ref_name }}"
    GITHUB_ACTION_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"


jobs:
    "j-o-b":
        name: job
        runs-on: ubuntu-latest

        steps:
            -   name: dump github context
                shell: bash
                run: |-
                    set -e

                    cat <<-'__ctx' >| context-github.json
                    ${{ toJSON(github) }}
                    __ctx

            -   name: dump inputs context
                shell: bash
                run: |-
                    set -e

                    cat <<-'__ctx' >| context-inputs.json
                    ${{ toJSON(inputs) }}
                    __ctx

            -   name: dump env context
                shell: bash
                run: |-
                    set -e

                    cat <<-'__ctx' >| context-env.json
                    ${{ toJSON(env) }}
                    __ctx

            -   name: upload artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: contexts
                    path: context-*.json


            -   name: messages
                shell: bash
                run: |-
                    set -e

                    COMMIT_MESSAGE=$(git log -1 $COMMIT_HASH --format=%B | sed 's/"/\\"/g')

                    echo "COMMIT_MESSAGE: "
                    echo $COMMIT_MESSAGE

                    echo ".github.event.head_commit.message: "
                    echo ">>>"
                    cat <<-'__msg'
                    ${{ .github.event.head_commit.message }}
                    __msg
                    echo "<<<"
