---
name: On Workflow Run

on:
    workflow_run:
        workflows: ["*"]
        types:
            - completed
            - requested

jobs:
    diag:
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read
            actions: read

        steps:
            -   name: dump contexts
                shell: bash
                run: |-
                    set -e

                    cat <<-'__ctx' >| context.json
                    {
                        "github_event": ${{ toJSON(github.event) }},
                        "github": ${{ toJSON(github) }}
                    }
                    __ctx

            -   name: upload artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: contexts-${{ github.job }}
                    path: context.json
