# sync branches
---
name: Sync branches
run-name: Sync branches from ${{ github.ref_name }}

"on":
    push:
        branches:
            - main

jobs:
    sync-main:
        if: github.ref_name == 'main'
        runs-on: ubuntu-latest

        permissions:
            contents: write
            pull-requests: write

        steps:
            -   name: Checkout
                uses: actions/checkout@v5
                with:
                    ref: dev
                    fetch-depth: 0

            -   name: Merge main into dev
                id: merger
                run: |-
                    git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
                    git config --global user.name "${{ github.actor }}"

                    if git merge --no-ff --no-edit ${{ github.sha }} ; then
                        git push
                    else
                        echo "merge_failed=true" | tee -a "${GITHUB_OUTPUT}"
                    fi

            -   name: "PR main → core/v2"
                if: steps.merger.outputs.merge_failed == 'true'
                uses: jdtx0/branch-sync@v1.5.1
                with:
                    GITHUB_TOKEN: ${{ github.token }}
                    FROM_BRANCH: "main"
                    TO_BRANCH: "dev"
